[package]
name = "stream_grep"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.27.0"
nix = { version = "0.29.0", features = ["signal"] }
tui-textarea = "0.7.0"
grep = "0.3.2"
tui-input = "0.11.1"
dark-light = "2.0.0"
strip-ansi-escapes = "0.2.1"
